'use strict';
// Lesson content transcribed from slides 5–9. Spanish glosses are web additions.
const modules = [
  {title:'My Identity',goal:'Students will introduce themselves and talk about aspects of their identity.',words:[['name','nombre'],['age','edad'],['family','familia'],['language','idioma'],['culture','cultura'],['community','comunidad'],['favorite','favorito/a']],expressions:['My name is Ana.','I am 11 years old.','I live in Quinchía.','I speak Spanish.','My favorite tradition is…'],task:'This Is Me',description:'Create a small identity card with drawings and simple English sentences.',note:'Choose which aspects of your identity you feel comfortable sharing.'},
  {title:'My Community',goal:'Students will identify and describe important places and people in their community.',words:[['school','escuela'],['house','casa'],['store','tienda'],['park','parque'],['church','iglesia'],['hospital','hospital'],['teacher','docente'],['farmer','agricultor/a']],expressions:['This is my community.','There is a school.','There are houses.','The school is important.'],task:'My Community Map',description:'Create a simple map of your community and label places in English.',note:'Compare rural and urban communities. What is similar? What is different?'},
  {title:'My Traditions',goal:'Students will describe a local tradition using basic English.',words:[['celebration','celebración'],['food','comida'],['music','música'],['dance','baile / bailar'],['family','familia'],['clothes','ropa'],['traditional','tradicional']],expressions:['This is a traditional celebration.','We eat traditional food.','We listen to music.','People dance.','My family celebrates together.'],task:'My Tradition Poster',description:'Create a poster about a tradition from your community.',note:''},
  {title:'My Culture and Other Cultures',goal:'Students will discover another culture and identify similarities and differences.',task:'Culture Around the World',description:'Explore a simple cultural tradition from another country. Compare it with a tradition from your community.',note:'Different cultures, equal value.',questions:['What is the tradition?','What food do people eat?','What music or activities are common?','Is it similar to your tradition?']}
];
// Links mapped by their positions on slide 11, not annotation order.
const activities = [
  {title:'Vocabulary Game',description:'Match words with pictures.',service:'WORDWALL',url:'https://wordwall.net/es/resource/118640658?wwmethod=link&wwshareintent=student'},
  {title:'My Community Map',description:'Create and present your community map.',service:'GOOGLE DOCS',url:'https://docs.google.com/document/d/1THMalY7S_PHcXbUOCPTQ22nrIhPlFU4fAUupwd6fA4c/edit?usp=sharing'},
  {title:'My Tradition Poster',description:'Describe a local tradition.',service:'GOOGLE DOCS',url:'https://docs.google.com/document/d/1xqaw8VOCe2gOm_LozrKxK2BsQC4QS3hoXtE87QGJUDI/edit?usp=sharing'},
  {title:'Culture Around the World',description:'Compare two cultural traditions.',service:'GOOGLE DRIVE',url:'https://drive.google.com/file/d/1ztwwAcew55IRHZqzM8KoAMRRF0FB5yXS/view?usp=sharing'},
  {title:'Culture Sharing',description:'Share something you learned about another culture.',service:'WORDWALL',url:'https://wordwall.net/es/resource/118642232?wwmethod=link&wwshareintent=student'}
];
const panel = document.querySelector('#module-panel');
const tabs = [...document.querySelectorAll('[data-module]')];
const practiceValues = {name:'',place:'',language:'',tradition:''};
function renderModule(index) {
  const lesson = modules[index];
  tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;});
  panel.setAttribute('aria-labelledby',`tab-${index}`);
  const content = lesson.words ? `<div class="lesson-grid"><div><p class="small-label">Vocabulary</p><div class="word-grid">${lesson.words.map(([en,es])=>`<button class="word" aria-pressed="false" data-english="${en}" data-spanish="${es}" aria-label="${en}: show Spanish translation"><span>${en}</span><small lang="es">Ver significado</small></button>`).join('')}</div></div><div><p class="small-label">Useful expressions</p><ul class="expressions">${lesson.expressions.map(t=>`<li>${t}</li>`).join('')}</ul></div></div>` : `<div class="country-grid"><div class="country"><b>Colombia</b><p>A local celebration</p></div><div class="country"><b>Mexico</b><p>Día de los Muertos</p></div><div class="country"><b>Japan</b><p>Hanami</p></div><div class="country"><b>USA</b><p>Thanksgiving</p></div></div><p class="resource-note" lang="es">Ejemplos del PDF. Las prácticas pueden variar entre personas, familias y comunidades.</p><p class="small-label">Think & share</p><ul class="expressions">${lesson.questions.map(t=>`<li>${t}</li>`).join('')}</ul>`;
  panel.innerHTML = `<div class="module-title-row"><span class="module-number">0${index+1}</span><h3>${lesson.title}</h3></div><p class="module-goal"><strong>Goal:</strong> ${lesson.goal}</p>${content}<div class="lesson-task"><p class="small-label">Your activity</p><h4>${lesson.task}</h4><p>${lesson.description}</p>${index>0?'<a class="text-link" href="#activities">Find the activity resource ↗</a>':''}</div>${lesson.note?`<p class="inclusion-note">${lesson.note}</p>`:''}${index===0?`<details class="practice"><summary>Try it here: my identity card <span lang="es">/ Practica aquí</span></summary><p class="resource-note" lang="es">Puedes usar datos inventados. Lo que escribas permanece en esta pestaña y se borra al recargar.</p><div class="practice-layout"><div class="practice-fields"><label>Your name / Nombre<input maxlength="60" data-field="name" autocomplete="off" placeholder="Ana"></label><label>Your town / Lugar<input maxlength="80" data-field="place" autocomplete="off" placeholder="Quinchía"></label><label>Your language / Idioma<input maxlength="60" data-field="language" autocomplete="off" placeholder="Spanish"></label><label>A tradition / Tradición<input maxlength="100" data-field="tradition" autocomplete="off" placeholder="a family celebration"></label></div><div class="identity-card"><h4>This is me!</h4><p>My name is <span data-preview="name">…</span>.</p><p>I live in <span data-preview="place">…</span>.</p><p>I speak <span data-preview="language">…</span>.</p><p>My favorite tradition is <span data-preview="tradition">…</span>.</p></div></div></details>`:''}`;
  panel.querySelectorAll('.word').forEach(button=>button.addEventListener('click',()=>{const show=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(show));button.querySelector('small').textContent=show?button.dataset.spanish:'Ver significado';button.setAttribute('aria-label',`${button.dataset.english}: ${show?button.dataset.spanish:'show Spanish translation'}`);}));
  panel.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;input.value=practiceValues[key];panel.querySelector(`[data-preview="${key}"]`).textContent=practiceValues[key]||'…';input.addEventListener('input',()=>{practiceValues[key]=input.value;panel.querySelector(`[data-preview="${key}"]`).textContent=input.value.trim()||'…';});});
}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>renderModule(index));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();renderModule(next);tabs[next].focus();}});});
document.querySelector('#activity-list').innerHTML=activities.map((activity,index)=>`<article class="activity"><div class="activity-top"><span class="activity-number">0${index+1}</span><span>${activity.service}</span></div><h3>${activity.title}</h3><p>${activity.description}</p><a href="${activity.url}" target="_blank" rel="noopener noreferrer" aria-label="Open ${activity.title} (new tab)">Open activity <span aria-hidden="true">↗</span></a><label class="activity-check"><input type="checkbox"> I practiced this activity</label></article>`).join('');
renderModule(0);
